import * as calculations from "./keyboardCalculations";

const keyboardData = [
    {
        key: '1',
        name: 'THERMAL SEQ2',
        brand: 'RAMA WORKS',
        type: 'unlimited',
        price: '$360',
        priceInt: 360,
        time: '2021-04-08',
        shipping: 'Q3 2022',
        progressInt: parseFloat(calculations.thermal_seq2),
        detailUrl: "https://ramaworks.store/products/thermal-seq2?variant=32876632735822",
        detailText: "https://thermal-seq2"
      },
      {
        key: '2',
        name: 'KARA',
        brand: 'RAMA WORKS',
        type: 'unlimited',
        price: '$160',
        priceInt: 160,
        time: '2021-12-31',
        shipping: 'Q2 2021',
        progressInt: parseFloat(calculations.kara),
        detailUrl: "https://ramaworks.store/products/kara", 
        detailText: "https://kara"
      },
      {
        key: '3',
        name: 'U80-A SEQ2',
        brand: 'RAMA WORKS',
        type: 'unlimited',
        price: '$400',
        time: '2020-10-31',
        shipping: 'Q2 2021',
        progressInt: parseFloat(calculations.u80a_seq2),
        detailUrl: "https://ramaworks.store/products/u80-a-seq2", 
        detailText: "https:u80-a-seq2"
      },
      {
        key: '4',
        name: 'FOUNDRY JULES',
        brand: 'RAMA WORKS',
        type: 'unlimited',
        price: '$400',
        priceInt: 400,
        time: '2020-04-15',
        shipping: 'Q2 2021',
        progressInt: parseFloat(calculations.foundary_jules),
        detailUrl: "https://ramaworks.store/products/jules", 
        detailText: "https://jules"
      },
      {
        key: '5',
        name: 'M50-A GRID',
        brand: 'RAMA WORKS',
        type: 'unlimited',
        price: '$300',
        priceInt: 300,
        time: '2020-05-31',
        shipping: 'Dec 2020',
        updateDate: '2021-07-21',
        delayTotalDays: '7 months',
        progressInt: parseFloat(calculations.m50a),
        detailUrl: "http://www.mechgroupbuys.com/keyboards/RAMA%20M50-A%20GRID", 
        detailText: "https://m50"
      },
      {
        key: '6',
        name: 'IRON165 R2',
        brand: 'Smith + Rune',
        type: 'unlimited',
        price: '$424',
        priceInt: 424,
        time: '2021-02-27',
        shipping: 'Mar 2022',
        progressInt: parseFloat(calculations.iron165_r2),
        detailUrl: "https://geekhack.org/index.php?topic=110985.0",
        detailText: "https://iron165-r2"
      },
      {
        key: '8',
        name: 'IM+',
        brand: 'Matrix Lab',
        type: "unlimited",
        price: '¥2599',
        priceInt: 2599 / 6.5,
        time: '2020-09-01',
        shipping: 'Q3 2021',
        progressInt: parseFloat(calculations.im),
        detail: "https:'请访问Matrix Lab QQ群'"
      },
      {
        key: '9',
        name: 'Matrix Vita',
        brand: 'Matrix Lab',
        type: "unlimited",
        price: '¥2699',
        priceInt: 2699 / 6.5,
        time: '2021-01-06',
        shipping: 'Q2 2021',
        progressInt: parseFloat(calculations.matrix65),
        detail: "https:'请访问Matrix Lab QQ群'"
      },
      {
        key: '10',
        name: 'Space80: Apollo',
        brand: 'Gray Studio',
        type: 'unlimited',
        price: '¥2699',
        priceInt: 2699 / 6.5,
        time: '2021-05-10',
        shipping: '2021-11-15',
        progressInt: parseFloat(calculations.space80),
        detailUrl: "https://www.zfrontier.com/app/flow/4KoRoAg8Qdd5", 
        detailText: "https://space80"
      },
      {
        key: '11',
        name: 'BOX75',
        brand: 'Lin Design Studio',
        type: 'unlimited',
        price: '$550',
        priceInt: 550,
        time: '2021-02-19',
        shipping: '2021年底',
        progressInt: parseFloat(calculations.box75),
        detailUrl: "https://www.zfrontier.com/app/flow/4bJOWrJoYrRo", 
        detailText: "https://box75"
      },
      {
        key: '12',
        name: 'Andromeda 仙女座',
        brand: 'ai03',
        type: "unlimited",
        price: '¥4999',
        priceInt: 4999 / 6.5,
        time: '2020-10-31',
        shipping: 'July 2021',
        progressInt: parseFloat(calculations.Andromeda),
        updateDate: '2021-07-31',
        detailUrl: "https://cannonkeys.com/products/gb-andromeda-keyboard-by-ai03-reference", 
        detailText: "https://andromeda"
      },
      {
        key: '13',
        name: 'Mach80',
        brand: 'MelGeek',
        type: "unlimited",
        price: '¥3299',
        priceInt: 3299 / 6.5,
        time: '2021-04-30',
        shipping: '4个月',
        progressInt: parseFloat(100 + calculations.mach80),
        detailUrl: "https://www.zfrontier.com/app/flow/D6MNdX0Ep0K5", 
        detailText: "https://mach80"
      },
      {
        key: '14',
        name: 'Leaf 65',
        brand: 'Fox Lab',
        type: 'unlimited',
        price: '¥2551',
        priceInt: 2551 / 6.5,
        time: '2021-01-02',
        shipping: 'Q3 2021',
        progressInt: parseFloat(calculations.leaf65),
        detailUrl: "https://www.zfrontier.com/app/flow/45aqZ63Yn85J", 
        detailText: "https://leaf65"
      },
      {
        key: '15',
        name: '1800mini',
        brand: 'Xikii',
        type: 'unlimited',
        price: '¥2499',
        priceInt: 2499 / 6.5,
        time: '2021-05-10',
        shipping: '三个月',
        progressInt: parseFloat(100 + calculations.mini1800),
        updateDate: '2021-08-10',
        detailUrl: "https://www.zfrontier.com/app/flow/2aVbAwVW8r8d", 
        detailText: "https://1800mini"
      },
      {
        key: '16',
        name: 'Master98',
        brand: 'Xikii',
        type: 'unlimited',
        price: '¥3670',
        priceInt: 3670 / 6.5,
        time: '2021-05-10',
        shipping: '三个月',
        updateDate: '2021-08-10',
        progressInt: 100,
        progressInt: parseFloat(calculations.master98),
        detailUrl: "https://www.zfrontier.com/app/flow/2aVbAwVW8r8d", 
        detailText: "https://master98"
      },
      {
        key: '17',
        name: 'i104 大爽',
        brand: 'Xikii',
        type: 'unlimited',
        price: '¥2980',
        priceInt: 2980 / 6.5,
        time: '2021-05-15开团，售完为止',
        shipping: 'June 2021',
        updateDate: '2021-08-09',
        delayTotalDays: '1 month',
        progressInt: parseFloat(calculations. i104),
        detailUrl: "https://www.zfrontier.com/app/flow/2JKxrvL3YlyO", 
        detailText: "https://i104"
      },
      {
        key: '18',
        name: 'WILBA.TECH SALVATION',
        brand: 'WILBA.TECH X Salvun',
        type: 'unlimited',
        price: '¥2285',
        priceInt: 2285 / 6.5,
        time: '2021-05-07',
        shipping: 'Dec. 2021',
        progressInt: parseFloat(calculations.salvation),
        detailUrl: "https://www.zfrontier.com/app/mch/1kwQEapmnrM1", 
        detailText: "https://salvation"
      },
      {
        key: '19',
        name: 'CYBERBOARD R2',
        brand: 'Angry Miao',
        type: 'unlimited',
        price: '¥3700',
        priceInt: 3700 / 6.5,
        time: '2021-05-28',
        shipping: 'July 2021',
        delayTotalDays: 'GB failure',
        updateDate: '2021-07-25',
        progressInt: parseFloat(calculations.cyberboard_r2),
        detailUrl: "https://www.angrymiao.com/cyberboard-r2/", 
        detailText: "https://cyberboard-r2/"
      },
      {
        key: '20',
        name: 'AM HATSU',
        brand: 'Angry Miao',
        type: 'unlimited',
        price: '$1600',
        priceInt: 1600,
        time: '2021-07-29',
        shipping: '2021-10-29',
        progressInt: parseFloat(calculations.am_hatsu),
        detailUrl: "https://www.angrymiao.com/am-hatsu/", 
        detailText: "https://am-hatsu"
      },
      {
        key: '21',
        name: 'Fuji65',
        brand: 'Sakura Studio',
        type: 'unlimited',
        price: '¥1399',
        priceInt: 1399 / 6.5,
        time: '2020-10-20',
        shipping: '已发货',
        progressInt: parseFloat(calculations.fuji65),
        detailUrl: "https://www.zfrontier.com/app/flow/epZ0136PqQmE", 
        detailText: "https://fuji65"
      },
  ];
  
  export default keyboardData;